function love.draw()

        love.graphics.setColor(255, 0, 0)
        love.graphics.print(puntuacion, 100, 100)
        love.graphics.print(puntuacion_max, 200, 100)

        love.graphics.circle("fill", objeto.bola.body:getX(), objeto.bola.body:getY(), objeto.bola.shape:getRadius())

        love.graphics.setColor(0, 255, 0)
        love.graphics.polygon("fill", objeto.suelo.body:getWorldPoints(objeto.suelo.shape:getPoints()))
        love.graphics.polygon("fill", objeto.pizquierda.body:getWorldPoints(objeto.pizquierda.shape:getPoints()))
        love.graphics.polygon("fill", objeto.pderecha.body:getWorldPoints(objeto.pderecha.shape:getPoints()))
        love.graphics.polygon("fill", objeto.cielo.body:getWorldPoints(objeto.cielo.shape:getPoints()))
end
